# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-64db72db-a73d-42cf-8c4f-e0ee77d247c7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-64db72db-a73d-42cf-8c4f-e0ee77d247c7".device = "/dev/disk/by-uuid/64db72db-a73d-42cf-8c4f-e0ee77d247c7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F757-45E2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-00d634db-fbb3-4fc3-aa29-397b289e0526"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
