#!/bin/sh

local_hook="$HOME"/.git_template.local/hooks/pre-commit

if [ -f "$local_hook" ]; then
  . "$local_hook"
fi

repo_hook='./hooks/pre-commit'
if [ -f "$repo_hook" ]; then
  . "$repo_hook"
fi
