#!/bin/sh

# git prepare-commit-msg hook for automatically prepending an issue key
# from the start of the current branch name to commit messages.
# https://bitbucket.org/snippets/atlassian/qedp7d

# check if commit is merge commit or a commit ammend
if [ "$2" = "merge" ] || [ "$2" = "commit" ]; then
    exit
fi

# If the commit message is not empty for any reason, bail
if head -1 "$1" | grep -ve '^$' > /dev/null; then
  exit
fi

ISSUE_KEY=$(git branch | grep -o "\* \(.*/\)*[A-Z]\{2,\}-[0-9]\+" | grep -o "[A-Z]\{2,\}-[0-9]\+")
if [ $? -ne 0 ]; then
    # no issue key in branch, use the default message
    exit
fi
# issue key matched from branch prefix, prepend to commit message
TEMP=$(mktemp /tmp/commitmsg-XXXXX)
(echo "$ISSUE_KEY $(cat  "$1")") > "$TEMP"
cat "$TEMP" > "$1"

local_hook="$HOME"/.git_template.local/hooks/prepare-commit-msg

if [ -f "$local_hook" ]; then
  . "$local_hook"
fi
